gemini-default:
  provider: gemini
  model: gemini-2.5-flash
  safety_settings:
    HARM_CATEGORY_DANGEROUS_CONTENT: BLOCK_MEDIUM_AND_ABOVE
    HARM_CATEGORY_HATE_SPEECH: BLOCK_ONLY_HIGH
    HARM_CATEGORY_HARASSMENT: BLOCK_LOW_AND_ABOVE
    HARM_CATEGORY_SEXUALLY_EXPLICIT: BLOCK_MEDIUM_AND_ABOVE

gemini-cold:
  provider: gemini
  model: gemini-2.0-flash
  temperature: 0.0
  safety_settings:
    HARM_CATEGORY_DANGEROUS_CONTENT: BLOCK_MEDIUM_AND_ABOVE
    HARM_CATEGORY_HATE_SPEECH: BLOCK_ONLY_HIGH
    HARM_CATEGORY_HARASSMENT: BLOCK_LOW_AND_ABOVE
    HARM_CATEGORY_SEXUALLY_EXPLICIT: BLOCK_MEDIUM_AND_ABOVE

gemini-crazy:
  provider: gemini
  model: gemini-2.5-flash
  temperature: 2.0
  safety_settings:
    HARM_CATEGORY_DANGEROUS_CONTENT: BLOCK_MEDIUM_AND_ABOVE
    HARM_CATEGORY_HATE_SPEECH: BLOCK_ONLY_HIGH
    HARM_CATEGORY_HARASSMENT: BLOCK_LOW_AND_ABOVE
    HARM_CATEGORY_SEXUALLY_EXPLICIT: BLOCK_MEDIUM_AND_ABOVE

openai-default:
  provider: openai
  model: gpt-4.1

ollama-gemma3:
  provider: ollama
  model: gemma3

