gemini-default:
  provider: gemini
  model: gemini-2.5-flash
  safety_settings:
    HARM_CATEGORY_DANGEROUS_CONTENT: BLOCK_MEDIUM_AND_ABOVE
    HARM_CATEGORY_HATE_SPEECH: BLOCK_ONLY_HIGH
    HARM_CATEGORY_HARASSMENT: BLOCK_LOW_AND_ABOVE
    HARM_CATEGORY_SEXUALLY_EXPLICIT: BLOCK_MEDIUM_AND_ABOVE

gemini-cold:
  provider: gemini
  model: gemini-2.0-flash
  temperature: 0.0
  safety_settings:
    HARM_CATEGORY_DANGEROUS_CONTENT: BLOCK_MEDIUM_AND_ABOVE
    HARM_CATEGORY_HATE_SPEECH: BLOCK_ONLY_HIGH
    HARM_CATEGORY_HARASSMENT: BLOCK_LOW_AND_ABOVE
    HARM_CATEGORY_SEXUALLY_EXPLICIT: BLOCK_MEDIUM_AND_ABOVE

gemini-crazy:
  provider: gemini
  model: gemini-2.5-flash
  temperature: 2.0
  safety_settings:
    HARM_CATEGORY_DANGEROUS_CONTENT: BLOCK_MEDIUM_AND_ABOVE
    HARM_CATEGORY_HATE_SPEECH: BLOCK_ONLY_HIGH
    HARM_CATEGORY_HARASSMENT: BLOCK_LOW_AND_ABOVE
    HARM_CATEGORY_SEXUALLY_EXPLICIT: BLOCK_MEDIUM_AND_ABOVE

openai-default:
  provider: openai
  model: gpt-4.1

ollama-gemma3:
  provider: ollama
  model: gemma3

embedding_model:
  provider: ollama
  model_name: "text-embedding-3-small"

vector_store:
  path: "src/data/vector_store"
  collection_name: "user_preferences_memory"

prompts:
  memory_extraction:
    input_variables: ["chat_history"]
    template:
      Analise o histórico de chat abaixo e extraia qualquer preferência do usuário que possa ser útil para interações futuras (ex: locais preferidos, tipo de comida, interesses, amigos, familiares etc.).
      Histórico do Chat: {chat_history}
      Se você encontrar uma ou mais preferências, liste-as de forma concisa. Se nenhuma preferência explícita for mencionada, responda exatamente com "N/A".

